export enum ActionType {
  CHANGE_TOKEN = "CHANGE_TOKEN",
  CHANGE_USERNAME = "CHANGE_USERNAME",
  CHANGE_ID = "CHANGE_ID",
  CHANGE_DRAWER = "CHANGE_DRAWER",
  CHANGE_THEME = "CHANGE_THEME",
  CHANGE_TABLE_SEARCH = "CHANGE_TABLE_SEARCH",
  CHANGE_USER = "CHANGE_USER",
}
